### ISSUE TITLE
noscript option requires Captcha::noCAPTCHA v0.12

### ISSUE THREAD

**Issue by veryrusty** [clarson/html-formhandlerx-field-nocaptcha#3]
As there is no version dependency on Captcha::noCAPTCHA, the `noscript` tests fail unless you have a release of Captcha::noCAPTCHA that supports that option.

**Comment by eserte** [comment]
Statistical analysis of test reports also shows that tests are failing for Captcha::noCAPTCHA < 0.12:
http://analysis.cpantesters.org/solved?distv=HTML-FormHandlerX-Field-noCAPTCHA-0.07#mod%3ACaptcha%3A%3AnoCAPTCHA

**Comment by clarson** [comment]
v0.08 released to address.  Please confirm.

**Comment by eserte** [comment]
Looks fine so far: http://fast-matrix.cpantesters.org/?dist=HTML-FormHandlerX-Field-noCAPTCHA%200.08

**Comment by veryrusty** [comment]
Looks good to me. Thanks @clarson !
